import type { EnemyDef, IntentDef, IntentKind } from '../types'

/**
 * Намерения врага. Игрок всегда видит следующее намерение заранее —
 * бой должен читаться, а не угадываться.
 */
export const INTENTS: Record<IntentKind, IntentDef> = {
  strike: {
    kind: 'strike',
    label: 'Удар',
    description: 'Обычная атака. Защита работает в полную силу.',
    power: 1,
    threat: 2,
  },
  heavy: {
    kind: 'heavy',
    label: 'Тяжёлый выпад',
    description: 'Мощный замах. Стоит поднять щит.',
    power: 1.7,
    threat: 3,
  },
  pierce: {
    kind: 'pierce',
    label: 'Пробой',
    description: 'Игнорирует большую часть защиты.',
    power: 1.1,
    threat: 3,
    ignoreDefense: 0.75,
  },
  drain: {
    kind: 'drain',
    label: 'Истощение',
    description: 'Слабый урон, но сжигает энергию цитадели.',
    power: 0.7,
    threat: 2,
    drainEnergy: 1,
  },
  shield: {
    kind: 'shield',
    label: 'Экранирование',
    description: 'Враг не атакует, но обрастает щитом.',
    power: 0,
    threat: 1,
    shieldSelf: 18,
  },
  regen: {
    kind: 'regen',
    label: 'Восстановление',
    description: 'Враг залечивает раны вместо атаки.',
    power: 0,
    threat: 1,
    healSelf: 22,
  },
  summon: {
    kind: 'summon',
    label: 'Призыв подкреплений',
    description: 'Слабый удар, но угроза резко растёт.',
    power: 0.6,
    threat: 8,
  },
}

export const ENEMIES: EnemyDef[] = [
  {
    id: 'scout-phage',
    name: 'Фаг-разведчик',
    title: 'Лёгкая угроза',
    description: 'Одиночный патрульный. Быстрый, хрупкий, предсказуемый.',
    hp: 34,
    attack: 6,
    armor: 0,
    pattern: ['strike', 'strike', 'heavy'],
    weakness: 'surge',
  },
  {
    id: 'clot-eater',
    name: 'Пожиратель сгустков',
    title: 'Средняя угроза',
    description: 'Питается тем же, чем строится империя. Сжигает энергию.',
    hp: 52,
    attack: 8,
    armor: 2,
    pattern: ['drain', 'strike', 'drain', 'heavy'],
    weakness: 'strike',
  },
  {
    id: 'gate-warden',
    name: 'Страж створа',
    title: 'Нексус региона I',
    description:
      'Первый противник, который умеет закрываться щитом. Учит главному приёму: «Экранирование» отвечается «Вскрытием».',
    // Обучающий босс: должен быть заметной ступенью, но проходимой без
    // идеальной игры — иначе первый регион становится стеной для новичка.
    hp: 78,
    attack: 8,
    armor: 6,
    pattern: ['strike', 'shield', 'heavy', 'strike', 'pierce'],
    weakness: 'rupture',
  },
  {
    id: 'drift-hunter',
    name: 'Охотник течений',
    title: 'Средняя угроза',
    description: 'Держится на дистанции и бьёт в разрывы обороны.',
    hp: 78,
    attack: 12,
    armor: 3,
    pattern: ['pierce', 'strike', 'heavy'],
    weakness: 'surge',
  },
  {
    id: 'splenic-keeper',
    name: 'Хранитель селезёнки',
    title: 'Страж хранилища',
    description: 'Не нападает первым, но чинит себя быстрее, чем вы его ломаете.',
    hp: 110,
    attack: 10,
    armor: 5,
    regen: 4,
    pattern: ['regen', 'strike', 'heavy', 'regen'],
    weakness: 'surge',
  },
  {
    id: 'lymph-lancer',
    name: 'Лимфатический копейщик',
    title: 'Тяжёлая угроза',
    description: 'Дисциплинированный боец с длинным замахом.',
    hp: 124,
    attack: 15,
    armor: 7,
    pattern: ['heavy', 'strike', 'pierce', 'heavy'],
    weakness: 'rupture',
  },
  {
    id: 'blast-swarm',
    name: 'Рой плазмобластов',
    title: 'Тяжёлая угроза',
    description: 'Множество мелких целей. Зовёт подкрепления — не затягивайте.',
    hp: 100,
    attack: 9,
    armor: 1,
    pattern: ['strike', 'summon', 'strike', 'drain'],
    weakness: 'surge',
  },
  {
    id: 'aortic-sentinel',
    name: 'Аортальный часовой',
    title: 'Нексус региона II',
    description: 'Броня, щит и терпение. Классический экзамен на подготовку.',
    hp: 240,
    attack: 19,
    armor: 12,
    regen: 3,
    pattern: ['shield', 'heavy', 'pierce', 'strike', 'regen'],
    weakness: 'rupture',
  },
  {
    id: 'oxy-reaver',
    name: 'Кислородный разоритель',
    title: 'Тяжёлая угроза',
    description: 'Перенасыщен энергией и бьёт без пауз.',
    hp: 190,
    attack: 24,
    armor: 8,
    pattern: ['heavy', 'heavy', 'strike'],
    weakness: 'guard',
  },
  {
    id: 'ridge-phalanx',
    name: 'Фаланга гребня',
    title: 'Тяжёлая угроза',
    description: 'Строй, который держит удар. Без вскрытия почти неуязвим.',
    hp: 230,
    attack: 20,
    armor: 18,
    pattern: ['shield', 'strike', 'heavy', 'shield'],
    weakness: 'rupture',
  },
  {
    id: 'ferro-ascetic',
    name: 'Железный аскет',
    title: 'Страж санктума',
    description: 'Почти не атакует, но лечится и ждёт, пока у вас кончится энергия.',
    hp: 205,
    attack: 14,
    armor: 10,
    regen: 8,
    pattern: ['regen', 'regen', 'pierce', 'strike'],
    weakness: 'surge',
  },
  {
    id: 'interferon-choir',
    name: 'Хор интерферона',
    title: 'Страж шпиля',
    description: 'Каждый его ход поднимает тревогу по всей системе.',
    hp: 215,
    attack: 17,
    armor: 9,
    pattern: ['summon', 'pierce', 'summon', 'heavy'],
    weakness: 'strike',
  },
  {
    id: 'vault-custodian',
    name: 'Кустод хранилища',
    title: 'Страж хранилища',
    description: 'Создан охранять и ничего больше. Делает это очень хорошо.',
    hp: 260,
    attack: 18,
    armor: 20,
    pattern: ['shield', 'heavy', 'shield', 'pierce'],
    weakness: 'rupture',
  },
  {
    id: 'archon-prototype',
    name: 'Прототип архонта',
    title: 'Страж кузницы',
    description: 'Незавершённый охотник высшего класса. Даже так — смертелен.',
    hp: 300,
    attack: 27,
    armor: 14,
    regen: 5,
    pattern: ['pierce', 'heavy', 'regen', 'drain', 'heavy'],
    weakness: 'surge',
  },
  {
    id: 'barrier-archon',
    name: 'Архонт барьера',
    title: 'Нексус региона III',
    description: 'Хранитель последней стены. Использует весь арсенал системы.',
    hp: 520,
    attack: 32,
    armor: 22,
    regen: 6,
    pattern: ['shield', 'pierce', 'heavy', 'regen', 'summon', 'heavy'],
    weakness: 'rupture',
  },
  {
    id: 'myelin-stalker',
    name: 'Миелиновый охотник',
    title: 'Смертельная угроза',
    description: 'Движется по нервам быстрее, чем кровь успевает среагировать.',
    hp: 380,
    attack: 34,
    armor: 12,
    pattern: ['pierce', 'pierce', 'heavy'],
    weakness: 'guard',
  },
  {
    id: 'synaptic-echo',
    name: 'Синаптическое эхо',
    title: 'Смертельная угроза',
    description: 'Повторяет ваши же удары. Истощает и не даёт передышки.',
    hp: 400,
    attack: 30,
    armor: 15,
    regen: 7,
    pattern: ['drain', 'heavy', 'regen', 'pierce'],
    weakness: 'strike',
  },
  {
    id: 'cortex-praetor',
    name: 'Кортикальный претор',
    title: 'Смертельная угроза',
    description: 'Командир последнего рубежа. Броня как у крепости.',
    hp: 460,
    attack: 33,
    armor: 26,
    pattern: ['shield', 'heavy', 'pierce', 'shield', 'heavy'],
    weakness: 'rupture',
  },
  {
    id: 'sovereign-immunis',
    name: 'Суверен Иммунис',
    title: 'Финальный противник',
    description: 'То, что всё это время считало кровь своей. Оно не защищается — оно отменяет.',
    hp: 900,
    attack: 44,
    armor: 30,
    regen: 12,
    pattern: ['summon', 'pierce', 'heavy', 'shield', 'drain', 'heavy', 'regen', 'pierce'],
    weakness: 'rupture',
  },
]

export const ENEMY_BY_ID: ReadonlyMap<string, EnemyDef> = new Map(ENEMIES.map(e => [e.id, e]))

export function getEnemy(id: string): EnemyDef | undefined {
  return ENEMY_BY_ID.get(id)
}

/** Противники, которых иммунная система присылает рейдом; выбор зависит от угрозы. */
/**
 * Кто приходит рейдом. Ступень выбирается по минимуму из уровня угрозы и
 * числа открытых регионов — рейдер никогда не опережает игрока по эпохе.
 * Состав ступеней намеренно легче одноимённых гарнизонов: рейд навязан.
 */
export const RAID_TABLE: ReadonlyArray<{ minThreat: number; enemies: readonly string[] }> = [
  { minThreat: 0, enemies: ['scout-phage', 'clot-eater'] },
  { minThreat: 70, enemies: ['drift-hunter', 'blast-swarm'] },
  { minThreat: 85, enemies: ['lymph-lancer', 'oxy-reaver', 'ridge-phalanx'] },
  { minThreat: 95, enemies: ['interferon-choir', 'myelin-stalker', 'cortex-praetor'] },
]
