import type { EventDef } from '../types'

/**
 * События между циклами.
 *
 * Мир игры был статичен: цикл всегда сводился к доходу, угрозе и иногда рейду.
 * Событие — это короткая развилка с явными последствиями: игрок видит, что
 * получит и чем заплатит, до того как выбрал. Скрытых исходов здесь нет
 * намеренно — решение должно быть решением, а не лотереей.
 */
export const EVENTS: EventDef[] = [
  {
    id: 'capillary-rupture',
    title: 'Разрыв капилляра',
    text: 'Одно из русел не выдержало давления. Течение уходит в ткань, и с каждым мгновением потери растут.',
    options: [
      {
        id: 'seal',
        label: 'Запечатать разрыв сгустками',
        outcome: 'Потратить сгустки, но сохранить поток.',
        resources: { clots: -25 },
        requires: { clots: 25 },
      },
      {
        id: 'bleed',
        label: 'Дать вытечь',
        outcome: 'Сберечь материал ценой целостности ядра.',
        integrity: -22,
      },
    ],
  },
  {
    id: 'immune-defector',
    title: 'Перебежчик',
    text: 'Одинокий фагоцит отбился от патруля и предлагает служить империи. Он не объясняет причин.',
    minCycle: 5,
    options: [
      {
        id: 'hire',
        label: 'Принять за эссенцию',
        outcome: 'Опыт и снижение угрозы: он знает маршруты патрулей.',
        resources: { essence: -4 },
        requires: { essence: 4 },
        threat: -14,
        xp: 40,
      },
      {
        id: 'consume',
        label: 'Поглотить',
        outcome: 'Сгустки и немного опыта, но иммунитет заметит пропажу.',
        resources: { clots: 40 },
        threat: 6,
        xp: 15,
      },
      {
        id: 'ignore',
        label: 'Отпустить',
        outcome: 'Ничего не происходит. Он уходит.',
      },
    ],
  },
  {
    id: 'hormonal-surge',
    title: 'Гормональный всплеск',
    text: 'Система впрыснула в кровоток команду, смысла которой империя не понимает. Русла на мгновение переполнены.',
    minCycle: 4,
    options: [
      {
        id: 'ride',
        label: 'Оседлать волну',
        outcome: 'Крупная разовая добыча ценой резкого роста угрозы.',
        resources: { plasma: 220, clots: 60 },
        threat: 16,
      },
      {
        id: 'hide',
        label: 'Переждать в тени',
        outcome: 'Ничего не взять, но маскировка вырастет.',
        masking: 20,
      },
    ],
  },
  {
    id: 'marrow-echo',
    title: 'Эхо костного мозга',
    text: 'Из глубины приходит сигнал рождения новых клеток. Его можно перехватить — или заглушить.',
    minCycle: 8,
    options: [
      {
        id: 'harvest',
        label: 'Перехватить поток',
        outcome: 'Много плазмы, но сигнал разойдётся по системе.',
        resources: { plasma: 280 },
        threat: 12,
      },
      {
        id: 'silence',
        label: 'Заглушить',
        outcome: 'Угроза падает, ресурсов нет.',
        threat: -20,
        masking: 10,
      },
      {
        id: 'study',
        label: 'Изучить структуру',
        outcome: 'Заметный опыт: империя понимает систему чуть лучше.',
        xp: 90,
      },
    ],
  },
  {
    id: 'clot-cannibals',
    title: 'Сгустки-каннибалы',
    text: 'Часть собственной массы вышла из-под контроля и пожирает соседние узлы. Империя столкнулась с собой.',
    minCycle: 10,
    minSectors: 5,
    options: [
      {
        id: 'purge',
        label: 'Вычистить силой',
        outcome: 'Немедленный бой с отбившейся массой.',
        fight: 'clot-eater',
      },
      {
        id: 'absorb',
        label: 'Поглотить обратно',
        outcome: 'Вернуть массу ценой целостности: она сопротивляется.',
        resources: { clots: 70 },
        integrity: -30,
      },
      {
        id: 'cede',
        label: 'Отдать им узел',
        outcome: 'Потерять ресурсы, но избежать потерь и шума.',
        resources: { plasma: -150 },
        requires: { plasma: 150 },
      },
    ],
  },
  {
    id: 'lymph-census',
    title: 'Лимфатическая перепись',
    text: 'Система пересчитывает клетки. Империю можно записать как норму — если подделать сигнатуру.',
    minCycle: 6,
    minThreat: 30,
    options: [
      {
        id: 'forge',
        label: 'Подделать сигнатуру',
        outcome: 'Дорого по эссенции, зато угроза резко падает.',
        resources: { essence: -6 },
        requires: { essence: 6 },
        threat: -30,
      },
      {
        id: 'hide-mass',
        label: 'Спрятать часть массы',
        outcome: 'Отдать сгустки, чтобы не попасть в отчёт.',
        resources: { clots: -50 },
        requires: { clots: 50 },
        threat: -15,
      },
      {
        id: 'defy',
        label: 'Не прятаться',
        outcome: 'Империю запишут как аномалию.',
        threat: 18,
        xp: 30,
      },
    ],
  },
  {
    id: 'oxygen-debt',
    title: 'Кислородный долг',
    text: 'Ткани требуют больше, чем система успевает доставить. Империя может помочь — или воспользоваться.',
    minCycle: 12,
    options: [
      {
        id: 'supply',
        label: 'Поделиться потоком',
        outcome: 'Отдать плазму, зато система на время перестанет искать врага.',
        resources: { plasma: -200 },
        requires: { plasma: 200 },
        threat: -25,
        masking: 12,
      },
      {
        id: 'exploit',
        label: 'Забрать своё',
        outcome: 'Эссенция и опыт, пока всем не до вас — но потом заметят.',
        resources: { essence: 10 },
        threat: 14,
        xp: 60,
      },
    ],
  },
  {
    id: 'dormant-forge',
    title: 'Спящий горн',
    text: 'В стенке сосуда обнаружен заглушённый узел синтеза. Его можно запустить, но он шумит.',
    minCycle: 14,
    minSectors: 8,
    options: [
      {
        id: 'ignite',
        label: 'Запустить',
        outcome: 'Постоянная прибавка к максимуму энергии ценой шума.',
        resources: { essence: -8 },
        requires: { essence: 8 },
        energy: 1,
        threat: 10,
      },
      {
        id: 'strip',
        label: 'Разобрать на материал',
        outcome: 'Много сгустков сразу, узел больше не пригодится.',
        resources: { clots: 120 },
      },
    ],
  },
  {
    id: 'immune-memory',
    title: 'Иммунная память',
    text: 'Система вспомнила предыдущие столкновения и подстроила патрули под вашу тактику.',
    minCycle: 16,
    minThreat: 50,
    options: [
      {
        id: 'rebuild',
        label: 'Перестроить контур',
        outcome: 'Сбросить накопленную угрозу дорогой ценой.',
        resources: { plasma: -180, clots: -60 },
        requires: { plasma: 180, clots: 60 },
        threat: -35,
      },
      {
        id: 'endure',
        label: 'Принять бой',
        outcome: 'Немедленное столкновение с подготовленным охотником.',
        fight: 'drift-hunter',
      },
    ],
  },
  {
    id: 'plasma-tide',
    title: 'Плазменный прилив',
    text: 'Редкое совпадение течений: русла на несколько мгновений отдают втрое больше обычного.',
    minCycle: 3,
    options: [
      {
        id: 'collect',
        label: 'Собрать всё',
        outcome: 'Крупная добыча плазмы без последствий. Такое бывает.',
        resources: { plasma: 180 },
        xp: 20,
      },
    ],
  },
  // ─── Средняя партия ───────────────────────────────────────────────────────

  {
    id: 'pressure-spike',
    title: 'Скачок давления',
    text: 'Система подняла давление во всём русле. Слабые стенки трещат, но течение стало щедрым.',
    minCycle: 12,
    repeatable: true,
    options: [
      {
        id: 'channel',
        label: 'Пустить через себя',
        outcome: 'Крупный сбор плазмы ценой части целостности.',
        resources: { plasma: 260 },
        integrity: -30,
        xp: 25,
      },
      {
        id: 'brace',
        label: 'Закрыться',
        outcome: 'Переждать всплеск. Ничего не получено, ничего не потеряно.',
      },
    ],
  },
  {
    id: 'patrol-rotation',
    title: 'Смена патрулей',
    text: 'Иммунитет перестраивает маршруты. На несколько циклов в сети появляются слепые пятна.',
    minCycle: 14,
    minSectors: 6,
    repeatable: true,
    options: [
      {
        id: 'slip',
        label: 'Пройти незамеченными',
        outcome: 'Заметное снижение угрозы: империю на время теряют из виду.',
        threat: -18,
        masking: 12,
      },
      {
        id: 'ambush',
        label: 'Ударить по стыку маршрутов',
        outcome: 'Опыт и сгустки, но иммунитет запомнит нападение.',
        resources: { clots: 70 },
        threat: 10,
        xp: 55,
      },
    ],
  },
  {
    id: 'starved-node',
    title: 'Голодающий узел',
    text: 'Один из захваченных узлов не получает питания. Он ещё держится, но недолго.',
    minCycle: 16,
    minSectors: 8,
    repeatable: true,
    options: [
      {
        id: 'feed',
        label: 'Прокормить из запасов',
        outcome: 'Плазма уходит, узел выживает и приносит опыт.',
        resources: { plasma: -140 },
        requires: { plasma: 140 },
        xp: 45,
      },
      {
        id: 'abandon',
        label: 'Бросить',
        outcome: 'Узел затихает. Иммунитет доволен: угроза падает, ядро теряет часть целостности.',
        integrity: -25,
        threat: -12,
      },
    ],
  },
  {
    id: 'ferrous-vein',
    title: 'Железистая жила',
    text: 'Разведка наткнулась на пласт, насыщенный железом. Добыть его можно, но не бесплатно.',
    minCycle: 18,
    repeatable: true,
    options: [
      {
        id: 'mine',
        label: 'Выработать жилу',
        outcome: 'Много сгустков за энергию цикла.',
        resources: { clots: 120 },
        energy: -3,
      },
      {
        id: 'refine-on-site',
        label: 'Перегнать на месте',
        outcome: 'Меньше сгустков, зато эссенция.',
        resources: { clots: 45, essence: 9 },
        energy: -2,
      },
    ],
  },
  {
    id: 'false-signal',
    title: 'Ложный сигнал',
    text: 'По сети идёт команда, которой никто не отдавал. Или отдавал, но не система.',
    minCycle: 20,
    repeatable: true,
    options: [
      {
        id: 'trace',
        label: 'Проследить источник',
        outcome: 'Опыт и снижение угрозы: империя понимает сеть чуть лучше.',
        threat: -14,
        xp: 60,
      },
      {
        id: 'amplify',
        label: 'Усилить и разослать',
        outcome: 'Иммунитет мечется впустую. Маскировка растёт, но плазма уходит.',
        resources: { plasma: -90 },
        requires: { plasma: 90 },
        masking: 26,
      },
    ],
  },
  {
    id: 'quarantine-order',
    title: 'Приказ о карантине',
    text: 'Система объявила участок заражённым. Под приказ попали и владения империи.',
    minCycle: 22,
    minThreat: 45,
    repeatable: true,
    options: [
      {
        id: 'comply',
        label: 'Затаиться',
        outcome: 'Цикл потерян, но империю вычёркивают из списка целей.',
        energy: -4,
        threat: -22,
      },
      {
        id: 'ignore-order',
        label: 'Работать как ни в чём не бывало',
        outcome: 'Доход сохранён, внимание иммунитета — тоже.',
        resources: { plasma: 120 },
        threat: 12,
      },
    ],
  },
  {
    id: 'severed-relay',
    title: 'Разорванная передача',
    text: 'Связь между двумя узлами оборвана. Логистика проседает, пока разрыв не закрыт.',
    minCycle: 24,
    minSectors: 10,
    repeatable: true,
    options: [
      {
        id: 'reroute',
        label: 'Проложить обход',
        outcome: 'Сгустки уходят на новую ветку, узлы снова связаны.',
        resources: { clots: -60 },
        requires: { clots: 60 },
        xp: 50,
      },
      {
        id: 'wait',
        label: 'Ждать, пока срастётся',
        outcome: 'Разрыв затянется сам, но империя недосчитается дохода.',
        resources: { plasma: -80 },
      },
    ],
  },
  {
    id: 'wandering-clotmass',
    title: 'Блуждающий сгусток',
    text: 'По руслу идёт масса чужих сгустков — не имперская и не иммунная. Она просто идёт.',
    minCycle: 26,
    repeatable: true,
    options: [
      {
        id: 'engulf',
        label: 'Поглотить',
        outcome: 'Крупная добыча сгустков и опыт.',
        resources: { clots: 130 },
        xp: 40,
      },
      {
        id: 'divert',
        label: 'Направить на патруль',
        outcome: 'Масса врезается в иммунный дозор. Угроза падает, добычи нет.',
        threat: -20,
        xp: 25,
      },
    ],
  },

  // ─── Поздняя партия ───────────────────────────────────────────────────────

  {
    id: 'imperial-census',
    title: 'Перепись империи',
    text: 'Владения разрослись настолько, что империя перестала знать саму себя. Пора считать.',
    minCycle: 40,
    minSectors: 16,
    repeatable: true,
    options: [
      {
        id: 'count',
        label: 'Пересчитать всё',
        outcome: 'Цикл уходит на учёт, но найденные излишки велики.',
        energy: -4,
        resources: { plasma: 320, clots: 90 },
        xp: 90,
      },
      {
        id: 'estimate',
        label: 'Обойтись оценкой',
        outcome: 'Быстро и приблизительно: скромная прибавка.',
        resources: { plasma: 90 },
        xp: 25,
      },
    ],
  },
  {
    id: 'archon-envoy',
    title: 'Посланник архонта',
    text: 'К границе вышел архонт без свиты. Он не нападает — он говорит.',
    minCycle: 45,
    minLevel: 7,
    options: [
      {
        id: 'listen',
        label: 'Выслушать',
        outcome: 'Знание дорого стоит: много опыта и снижение угрозы.',
        resources: { essence: -14 },
        requires: { essence: 14 },
        threat: -25,
        xp: 220,
      },
      {
        id: 'strike',
        label: 'Ударить первым',
        outcome: 'Немедленный бой с архонтом барьера.',
        fight: 'barrier-archon',
      },
    ],
  },
  {
    id: 'systemic-fever',
    title: 'Системная лихорадка',
    text: 'Температура сети поднялась. Всё ускоряется — и рост империи, и внимание к ней.',
    minCycle: 50,
    repeatable: true,
    options: [
      {
        id: 'burn',
        label: 'Гнать на жаре',
        outcome: 'Большая добыча и опыт, но угроза скакнёт.',
        resources: { plasma: 400, clots: 120 },
        threat: 18,
        xp: 120,
      },
      {
        id: 'cool',
        label: 'Сбросить темп',
        outcome: 'Часть целостности восстановлена, угроза падает.',
        integrity: 60,
        threat: -16,
      },
    ],
  },
  {
    id: 'marrow-tribute',
    title: 'Дань костного мозга',
    text: 'Мозг предлагает поставки в обмен на невмешательство. Империя может согласиться — или взять сама.',
    minCycle: 55,
    minSectors: 20,
    repeatable: true,
    options: [
      {
        id: 'accept',
        label: 'Принять дань',
        outcome: 'Стабильная выплата эссенцией без последствий.',
        resources: { essence: 26 },
        xp: 60,
      },
      {
        id: 'seize',
        label: 'Взять всё',
        outcome: 'Куда больше эссенции, но мозг поднимет тревогу.',
        resources: { essence: 55 },
        threat: 20,
        xp: 90,
      },
    ],
  },
  {
    id: 'old-empire',
    title: 'Следы прежней империи',
    text: 'В глубине русла — остатки чего-то, что уже пыталось сделать то же самое. И не сумело.',
    minCycle: 60,
    minSectors: 22,
    options: [
      {
        id: 'study-ruins',
        label: 'Изучить останки',
        outcome: 'Очень много опыта: чужие ошибки дешевле своих.',
        xp: 320,
      },
      {
        id: 'salvage',
        label: 'Разобрать на материал',
        outcome: 'Крупные запасы всех трёх ресурсов.',
        resources: { plasma: 500, clots: 200, essence: 30 },
      },
    ],
  },
  {
    id: 'immune-schism',
    title: 'Раскол иммунитета',
    text: 'Две ветви иммунной системы не сошлись в том, кого считать врагом. Пока они спорят, империю не трогают.',
    minCycle: 65,
    minThreat: 50,
    repeatable: true,
    options: [
      {
        id: 'fuel',
        label: 'Подлить масла',
        outcome: 'Раскол углубляется: угроза резко падает, эссенция уходит.',
        resources: { essence: -18 },
        requires: { essence: 18 },
        threat: -40,
        xp: 110,
      },
      {
        id: 'use-pause',
        label: 'Воспользоваться паузой',
        outcome: 'Пока они заняты друг другом, империя собирает вдвое.',
        resources: { plasma: 380, clots: 140 },
        xp: 70,
      },
    ],
  },
  {
    id: 'terminal-pressure',
    title: 'Предельное давление',
    text: 'Система давит на всё сразу. Это уже не проверка — это попытка закончить.',
    minCycle: 80,
    minThreat: 65,
    repeatable: true,
    repeatCooldown: 22,
    options: [
      {
        id: 'hold',
        label: 'Держать все узлы',
        outcome: 'Огромный расход, но империя выстоит без потерь.',
        resources: { plasma: -420, clots: -150 },
        requires: { plasma: 420, clots: 150 },
        threat: -30,
        xp: 140,
      },
      {
        id: 'give',
        label: 'Отдать периферию',
        outcome: 'Целостность просядет, зато давление спадёт само.',
        integrity: -90,
        threat: -45,
      },
    ],
  },

  // ─── Малые повторяемые: фон партии ────────────────────────────────────────

  {
    id: 'stray-current',
    title: 'Шальное течение',
    text: 'Русло на миг повернуло не туда. Мелочь, но её можно поймать.',
    minCycle: 8,
    repeatable: true,
    repeatCooldown: 18,
    options: [
      {
        id: 'catch',
        label: 'Поймать',
        outcome: 'Немного плазмы и опыта.',
        resources: { plasma: 70 },
        xp: 15,
      },
    ],
  },
  {
    id: 'clogged-channel',
    title: 'Забитый канал',
    text: 'Один из каналов встал. Пробку надо либо пробить, либо обойти.',
    minCycle: 10,
    repeatable: true,
    repeatCooldown: 20,
    options: [
      {
        id: 'clear',
        label: 'Пробить',
        outcome: 'Энергия уходит, канал снова работает.',
        energy: -2,
        resources: { plasma: 60 },
        xp: 20,
      },
      {
        id: 'bypass',
        label: 'Обойти',
        outcome: 'Сгустки на новый обход, зато без потери хода.',
        resources: { clots: -30 },
        requires: { clots: 30 },
        xp: 20,
      },
    ],
  },
  {
    id: 'silent-cycle',
    title: 'Тихий цикл',
    text: 'Ничего не происходит. В сети, которая никогда не молчит, это само по себе странно.',
    minCycle: 15,
    repeatable: true,
    repeatCooldown: 24,
    options: [
      {
        id: 'rest',
        label: 'Воспользоваться тишиной',
        outcome: 'Часть целостности восстановлена.',
        integrity: 40,
      },
      {
        id: 'attune',
        label: 'Прислушаться',
        outcome: 'Маскировка растёт: империя учится молчать вместе с сетью.',
        masking: 18,
        xp: 25,
      },
    ],
  },
  {
    id: 'defector-again',
    title: 'Ещё один перебежчик',
    text: 'Слух о первом разошёлся. Теперь они приходят сами.',
    minCycle: 30,
    minLevel: 5,
    repeatable: true,
    options: [
      {
        id: 'recruit',
        label: 'Принять',
        outcome: 'Опыт и снижение угрозы за эссенцию.',
        resources: { essence: -8 },
        requires: { essence: 8 },
        threat: -16,
        xp: 80,
      },
      {
        id: 'devour',
        label: 'Поглотить',
        outcome: 'Сгустки вместо союзника.',
        resources: { clots: 90 },
        threat: 8,
        xp: 30,
      },
    ],
  },
]

export const EVENT_BY_ID: ReadonlyMap<string, EventDef> = new Map(EVENTS.map(e => [e.id, e]))
