import type { DoctrineDef, DoctrinePath, ModuleDef, TechDef } from '../types'

/**
 * Модули цитадели — 30 штук в пяти ветках.
 * Ветка открывается по tier: модуль требует предыдущий в своей ветке.
 * Эффекты указаны «за уровень» и умножаются на текущий уровень.
 */
export const MODULES: ModuleDef[] = [
  // ─── Ветка: Плазменный поток ──────────────────────────────────────────────
  {
    id: 'pulse-harvester',
    name: 'Пульсовый жнец',
    description: 'Ритмичные сокращения выжимают из русла больше плазмы.',
    branch: 'Плазменный поток',
    tier: 1,
    maxLevel: 3,
    costs: [{ plasma: 45 }, { plasma: 90, clots: 12 }, { plasma: 180, clots: 30 }],
    effects: { plasmaYield: 0.049 },
  },
  {
    id: 'osmotic-web',
    name: 'Осмотическая сеть',
    description: 'Вытягивает плазму даже из соседних, ещё не захваченных русел.',
    branch: 'Плазменный поток',
    tier: 2,
    maxLevel: 3,
    costs: [
      { plasma: 140, clots: 20 },
      { plasma: 260, clots: 45 },
      { plasma: 460, clots: 80 },
    ],
    effects: { plasmaYield: 0.056, xpYield: 0.017 },
    requires: ['pulse-harvester'],
  },
  {
    id: 'blood-matrix',
    name: 'Кровяная матрица',
    description: 'Перестраивает переработку: каждый сгусток выходит плотнее.',
    branch: 'Плазменный поток',
    tier: 3,
    maxLevel: 3,
    costs: [
      { plasma: 300, clots: 60, essence: 3 },
      { plasma: 520, clots: 110, essence: 6 },
      { plasma: 880, clots: 190, essence: 10 },
    ],
    effects: { clotYield: 0.07, plasmaYield: 0.028 },
    requires: ['osmotic-web'],
  },
  {
    id: 'sanguine-pylon',
    name: 'Сангвинный пилон',
    description: 'Стабилизирует поток по всей сети, ускоряя всё сразу.',
    branch: 'Плазменный поток',
    tier: 4,
    maxLevel: 3,
    costs: [
      { plasma: 620, clots: 150, essence: 10 },
      { plasma: 1050, clots: 260, essence: 18 },
      { plasma: 1700, clots: 420, essence: 30 },
    ],
    effects: { plasmaYield: 0.063, clotYield: 0.042, essenceYield: 0.035 },
    requires: ['blood-matrix'],
  },
  {
    id: 'crimson-forge',
    name: 'Багровый горн',
    description: 'Уникальный модуль из Синтез-купола архонтов. Перековывает всё подряд.',
    branch: 'Плазменный поток',
    tier: 5,
    maxLevel: 3,
    costs: [
      { plasma: 900, clots: 260, essence: 20 },
      { plasma: 1500, clots: 430, essence: 34 },
      { plasma: 2400, clots: 700, essence: 55 },
    ],
    effects: { clotYield: 0.087, essenceYield: 0.052, attack: 3 },
    requires: ['sanguine-pylon'],
  },
  {
    id: 'singularity-heart',
    name: 'Сердце сингулярности',
    description: 'Уникальный модуль из Горна сингулярности. Достроенный проект системы.',
    branch: 'Плазменный поток',
    tier: 6,
    maxLevel: 3,
    costs: [
      { plasma: 1600, clots: 520, essence: 45 },
      { plasma: 2600, clots: 860, essence: 72 },
      { plasma: 4200, clots: 1400, essence: 115 },
    ],
    effects: { plasmaYield: 0.105, clotYield: 0.105, essenceYield: 0.105, xpYield: 0.07 },
    requires: ['crimson-forge'],
  },

  // ─── Ветка: Штурмовой контур ──────────────────────────────────────────────
  {
    id: 'hem-arsenal',
    name: 'Гемо-арсенал',
    description: 'Первый настоящий оружейный контур цитадели.',
    branch: 'Штурмовой контур',
    tier: 1,
    maxLevel: 3,
    costs: [{ clots: 25 }, { clots: 55, plasma: 60 }, { clots: 110, plasma: 140 }],
    effects: { attack: 4 },
  },
  {
    id: 'forge-core',
    name: 'Ядро кузницы',
    description: 'Уникальный модуль из Кузницы эритроцитов. Отливает боевые контуры на ходу.',
    branch: 'Штурмовой контур',
    tier: 2,
    maxLevel: 3,
    costs: [
      { clots: 70, plasma: 90 },
      { clots: 140, plasma: 190 },
      { clots: 260, plasma: 360 },
    ],
    effects: { attack: 5, pierce: 2 },
    requires: ['hem-arsenal'],
  },
  {
    id: 'lance-array',
    name: 'Батарея копий',
    description: 'Концентрирует удар в одну точку, проходя сквозь броню.',
    branch: 'Штурмовой контур',
    tier: 3,
    maxLevel: 3,
    costs: [
      { clots: 180, plasma: 240, essence: 4 },
      { clots: 320, plasma: 420, essence: 8 },
      { clots: 560, plasma: 740, essence: 14 },
    ],
    effects: { attack: 6, pierce: 4 },
    requires: ['forge-core'],
  },
  {
    id: 'rally-node',
    name: 'Узел сбора',
    description: 'Уникальный модуль из Синтез-камеры. Держит наступление на ходу.',
    branch: 'Штурмовой контур',
    tier: 4,
    maxLevel: 3,
    costs: [
      { clots: 340, plasma: 460, essence: 10 },
      { clots: 580, plasma: 780, essence: 18 },
      { clots: 960, plasma: 1300, essence: 30 },
    ],
    effects: { attack: 8, maxEnergy: 1 },
    requires: ['lance-array'],
  },
  {
    id: 'scarlet-arsenal',
    name: 'Алый арсенал',
    description: 'Полный боевой комплект имперской цитадели.',
    branch: 'Штурмовой контур',
    tier: 5,
    maxLevel: 3,
    costs: [
      { clots: 700, plasma: 900, essence: 22 },
      { clots: 1150, plasma: 1500, essence: 36 },
      { clots: 1900, plasma: 2500, essence: 60 },
    ],
    effects: { attack: 12, pierce: 6 },
    requires: ['rally-node'],
  },
  {
    id: 'apex-lance',
    name: 'Пиковое копьё',
    description: 'Оружие, спроектированное против архонтов.',
    branch: 'Штурмовой контур',
    tier: 6,
    maxLevel: 3,
    costs: [
      { clots: 1500, plasma: 1900, essence: 50 },
      { clots: 2400, plasma: 3100, essence: 80 },
      { clots: 3900, plasma: 5000, essence: 130 },
    ],
    effects: { attack: 18, pierce: 10 },
    requires: ['scarlet-arsenal'],
  },

  // ─── Ветка: Цитадель ──────────────────────────────────────────────────────
  {
    id: 'clot-plating',
    name: 'Сгустковая броня',
    description: 'Простая, надёжная, спасает на ранних циклах.',
    branch: 'Цитадель',
    tier: 1,
    maxLevel: 3,
    costs: [
      { clots: 20, plasma: 40 },
      { clots: 48, plasma: 90 },
      { clots: 100, plasma: 190 },
    ],
    effects: { defense: 2, maxIntegrity: 15 },
  },
  {
    id: 'fibrin-lattice',
    name: 'Фибриновая решётка',
    description: 'Распределяет урон по всей структуре ядра.',
    branch: 'Цитадель',
    tier: 2,
    maxLevel: 3,
    costs: [
      { clots: 90, plasma: 150 },
      { clots: 180, plasma: 290 },
      { clots: 330, plasma: 540 },
    ],
    effects: { defense: 3, maxIntegrity: 25, regen: 2 },
    requires: ['clot-plating'],
  },
  {
    id: 'marrow-anchor',
    name: 'Костномозговой якорь',
    description: 'Связь с источником восстановления: ядро чинится само.',
    branch: 'Цитадель',
    tier: 3,
    maxLevel: 3,
    costs: [
      { clots: 220, plasma: 340, essence: 5 },
      { clots: 400, plasma: 610, essence: 9 },
      { clots: 700, plasma: 1050, essence: 16 },
    ],
    effects: { defense: 4, maxIntegrity: 45, regen: 5 },
    requires: ['fibrin-lattice'],
  },
  {
    id: 'endothelial-wall',
    name: 'Эндотелиальная стена',
    description: 'Живая броня, скопированная с бастиона артерий.',
    branch: 'Цитадель',
    tier: 4,
    maxLevel: 3,
    costs: [
      { clots: 480, plasma: 700, essence: 12 },
      { clots: 820, plasma: 1200, essence: 20 },
      { clots: 1350, plasma: 1950, essence: 34 },
    ],
    effects: { defense: 7, maxIntegrity: 80, regen: 7 },
    requires: ['marrow-anchor'],
  },
  {
    id: 'aegis-core',
    name: 'Эгида ядра',
    description: 'Абсолютный приоритет выживания над всем остальным.',
    branch: 'Цитадель',
    tier: 5,
    maxLevel: 3,
    costs: [
      { clots: 900, plasma: 1300, essence: 26 },
      { clots: 1500, plasma: 2100, essence: 42 },
      { clots: 2400, plasma: 3400, essence: 68 },
    ],
    effects: { defense: 11, maxIntegrity: 130, regen: 12 },
    requires: ['endothelial-wall'],
  },

  // ─── Ветка: Тени ──────────────────────────────────────────────────────────
  {
    id: 'veil-shroud',
    name: 'Покров вуали',
    description: 'Гасит биомаркеры империи, замедляя рост угрозы.',
    branch: 'Тени',
    tier: 1,
    maxLevel: 3,
    costs: [
      { plasma: 60, clots: 10 },
      { plasma: 130, clots: 26 },
      { plasma: 260, clots: 55 },
    ],
    effects: { masking: 3, suppression: 0.05 },
  },
  {
    id: 'silent-veil',
    name: 'Безмолвная вуаль',
    description: 'Империя перестаёт выглядеть как аномалия.',
    branch: 'Тени',
    tier: 2,
    maxLevel: 3,
    costs: [
      { plasma: 190, clots: 40, essence: 2 },
      { plasma: 350, clots: 75, essence: 4 },
      { plasma: 620, clots: 135, essence: 8 },
    ],
    effects: { masking: 4, suppression: 0.07 },
    requires: ['veil-shroud'],
  },
  {
    id: 'phase-screen',
    name: 'Фазовый экран',
    description: 'Сдвигает сигнатуру потока — патрули проходят мимо.',
    branch: 'Тени',
    tier: 3,
    maxLevel: 3,
    costs: [
      { plasma: 420, clots: 90, essence: 7 },
      { plasma: 720, clots: 160, essence: 12 },
      { plasma: 1200, clots: 270, essence: 20 },
    ],
    effects: { masking: 5, suppression: 0.08, defense: 3 },
    requires: ['silent-veil'],
  },
  {
    id: 'null-signature',
    name: 'Нулевая сигнатура',
    description: 'Для иммунной системы империи больше не существует. Почти.',
    branch: 'Тени',
    tier: 4,
    maxLevel: 3,
    costs: [
      { plasma: 900, clots: 200, essence: 16 },
      { plasma: 1500, clots: 340, essence: 26 },
      { plasma: 2400, clots: 560, essence: 42 },
    ],
    effects: { masking: 7, suppression: 0.1 },
    requires: ['phase-screen'],
  },

  // ─── Ветка: Логистика ─────────────────────────────────────────────────────
  // Вторая ось развития помимо военной: не «бить сильнее» и не «прятаться
  // лучше», а дотягиваться дальше. Без неё дальние богатые секторы теряют
  // на доставке больше половины дохода.
  {
    id: 'flow-relay',
    name: 'Проточный ретранслятор',
    description: 'Расширяет зону полной отдачи вокруг каждого узла сети.',
    branch: 'Логистика',
    tier: 1,
    maxLevel: 3,
    costs: [
      { plasma: 90, clots: 18 },
      { plasma: 200, clots: 45 },
      { plasma: 400, clots: 95 },
    ],
    effects: { logistics: 1 },
  },
  {
    id: 'pressure-column',
    name: 'Напорная колонна',
    description: 'Держит давление на дальних маршрутах: потери на доставке падают.',
    branch: 'Логистика',
    tier: 2,
    maxLevel: 3,
    costs: [
      { plasma: 260, clots: 60, essence: 3 },
      { plasma: 460, clots: 110, essence: 6 },
      { plasma: 800, clots: 190, essence: 11 },
    ],
    effects: { logistics: 1, plasmaYield: 0.028 },
    requires: ['flow-relay'],
  },
  {
    id: 'vascular-grid',
    name: 'Сосудистая решётка',
    description: 'Сеть перестаёт зависеть от расстояния почти полностью.',
    branch: 'Логистика',
    tier: 3,
    maxLevel: 3,
    costs: [
      { plasma: 620, clots: 150, essence: 9 },
      { plasma: 1050, clots: 260, essence: 16 },
      { plasma: 1700, clots: 430, essence: 26 },
    ],
    effects: { logistics: 2, clotYield: 0.035 },
    requires: ['pressure-column'],
  },
  {
    id: 'omni-conduit',
    name: 'Всеобщая магистраль',
    description: 'Империя доставляет всё и отовсюду, будто расстояний нет.',
    branch: 'Логистика',
    tier: 4,
    maxLevel: 2,
    costs: [
      { plasma: 1500, clots: 380, essence: 24 },
      { plasma: 2600, clots: 660, essence: 40 },
    ],
    effects: { logistics: 3, plasmaYield: 0.042, essenceYield: 0.042 },
    requires: ['vascular-grid'],
  },

  // ─── Ветка: Энергетический купол ──────────────────────────────────────────
  {
    id: 'energy-loop',
    name: 'Энергетический контур',
    description: 'Замкнутая петля, дающая цитадели лишнее действие за цикл.',
    branch: 'Энергетический купол',
    tier: 1,
    maxLevel: 2,
    costs: [
      { plasma: 110, clots: 22 },
      { plasma: 300, clots: 70, essence: 3 },
    ],
    effects: { maxEnergy: 1 },
  },
  {
    id: 'nerve-lattice',
    name: 'Нервная решётка',
    description: 'Ускоряет реакцию и добавляет опыта каждому действию.',
    branch: 'Энергетический купол',
    tier: 2,
    maxLevel: 3,
    costs: [
      { plasma: 320, clots: 70, essence: 4 },
      { plasma: 560, clots: 130, essence: 8 },
      { plasma: 950, clots: 220, essence: 14 },
    ],
    effects: { xpYield: 0.042, masking: 1 },
    requires: ['energy-loop'],
  },
  {
    id: 'surge-capacitor',
    name: 'Всплесковый накопитель',
    description: 'Накапливает импульс между циклами.',
    branch: 'Энергетический купол',
    tier: 3,
    maxLevel: 2,
    costs: [
      { plasma: 700, clots: 170, essence: 10 },
      { plasma: 1300, clots: 320, essence: 20 },
    ],
    effects: { maxEnergy: 1, attack: 4 },
    requires: ['nerve-lattice'],
  },
  {
    id: 'aurora-dome',
    name: 'Купол зари',
    description: 'Венец энергетической ветки: цитадель почти не устаёт.',
    branch: 'Энергетический купол',
    tier: 4,
    maxLevel: 2,
    costs: [
      { plasma: 1600, clots: 400, essence: 30 },
      { plasma: 2800, clots: 720, essence: 52 },
    ],
    effects: { maxEnergy: 1, regen: 8, xpYield: 0.052 },
    requires: ['surge-capacitor'],
  },
]

/**
 * Доктрины: три взаимоисключающих пути.
 * Выбрав путь, игрок закрывает два других навсегда — это главное решение забега.
 */
export const DOCTRINE_PATHS: Record<
  DoctrinePath,
  { id: DoctrinePath; name: string; motto: string; description: string }
> = {
  reaver: {
    id: 'reaver',
    name: 'Путь Разорителя',
    motto: 'Быстрее, чем система успеет ответить',
    description:
      'Ставка на урон и скорость захвата. Империя берёт всё сразу и не оглядывается на угрозу.',
  },
  warden: {
    id: 'warden',
    name: 'Путь Хранителя',
    motto: 'Пусть придут. Стена не сдвинется',
    description:
      'Ставка на целостность, защиту и переживание рейдов. Медленно, зато почти неуязвимо.',
  },
  weaver: {
    id: 'weaver',
    name: 'Путь Ткача',
    motto: 'Империя, которой никто не видел',
    description:
      'Ставка на маскировку, экономику и подавление угрозы. Побеждает тот, кого не искали.',
  },
}

export const DOCTRINES: DoctrineDef[] = [
  // Разоритель
  {
    id: 'reaver-1',
    name: 'Жажда',
    description: 'Каждый удар цитадели становится тяжелее.',
    path: 'reaver',
    tier: 1,
    maxLevel: 3,
    costs: [{ essence: 4 }, { essence: 9, clots: 90 }, { essence: 16, clots: 200 }],
    effects: { attack: 6 },
  },
  {
    id: 'reaver-2',
    name: 'Кровавая жатва',
    description: 'Захваты приносят больше сгустков и опыта.',
    path: 'reaver',
    tier: 2,
    maxLevel: 3,
    costs: [
      { essence: 10, clots: 140 },
      { essence: 18, clots: 280 },
      { essence: 30, clots: 500 },
    ],
    effects: { clotYield: 0.2, xpYield: 0.2 },
    requires: ['reaver-1'],
  },
  // Развилка Разорителя: точечная резня против широкой волны.
  {
    id: 'reaver-3a',
    name: 'Резня',
    description: 'Всё в один удар: пробитие и урон против одиночных целей.',
    path: 'reaver',
    fork: 'reaver-3',
    tier: 3,
    maxLevel: 3,
    costs: [
      { essence: 20, clots: 320 },
      { essence: 34, clots: 560 },
      { essence: 55, clots: 900 },
    ],
    effects: { pierce: 10, attack: 8 },
    requires: ['reaver-2'],
  },
  {
    id: 'reaver-3b',
    name: 'Волна',
    description: 'Каждая победа гасит внимание системы и кормит цитадель.',
    path: 'reaver',
    fork: 'reaver-3',
    tier: 3,
    maxLevel: 3,
    costs: [
      { essence: 20, clots: 320 },
      { essence: 34, clots: 560 },
      { essence: 55, clots: 900 },
    ],
    effects: { attack: 5, suppression: 0.1, clotYield: 0.18 },
    requires: ['reaver-2'],
  },
  {
    id: 'reaver-4',
    name: 'Багровый апофеоз',
    description: 'Предел агрессии: цитадель бьёт сильнее, чем должна уметь.',
    path: 'reaver',
    tier: 4,
    maxLevel: 3,
    costs: [
      { essence: 40, clots: 700, plasma: 900 },
      { essence: 65, clots: 1100, plasma: 1500 },
      { essence: 100, clots: 1800, plasma: 2400 },
    ],
    effects: { attack: 16, pierce: 8, maxEnergy: 1 },
    requires: ['reaver-3a', 'reaver-3b'],
    requiresAny: true,
  },

  // Хранитель
  {
    id: 'warden-1',
    name: 'Непоколебимость',
    description: 'Ядро выдерживает то, что раньше пробивало насквозь.',
    path: 'warden',
    tier: 1,
    maxLevel: 3,
    costs: [{ essence: 4 }, { essence: 9, plasma: 130 }, { essence: 16, plasma: 280 }],
    effects: { defense: 5, maxIntegrity: 30 },
  },
  {
    id: 'warden-2',
    name: 'Круговорот',
    description: 'Цитадель восстанавливается каждый цикл.',
    path: 'warden',
    tier: 2,
    maxLevel: 3,
    costs: [
      { essence: 10, plasma: 200 },
      { essence: 18, plasma: 380 },
      { essence: 30, plasma: 680 },
    ],
    effects: { regen: 10, maxIntegrity: 40 },
    requires: ['warden-1'],
  },
  // Развилка Хранителя: глухая стена против живучести и восстановления.
  {
    id: 'warden-3a',
    name: 'Стена имени крови',
    description: 'Рейды разбиваются о защиту, не доходя до ядра.',
    path: 'warden',
    fork: 'warden-3',
    tier: 3,
    maxLevel: 3,
    costs: [
      { essence: 20, plasma: 460, clots: 160 },
      { essence: 34, plasma: 800, clots: 300 },
      { essence: 55, plasma: 1300, clots: 500 },
    ],
    effects: { defense: 14, maxIntegrity: 50 },
    requires: ['warden-2'],
  },
  {
    id: 'warden-3b',
    name: 'Живая ткань',
    description: 'Ядро не столько держит удар, сколько мгновенно зарастает.',
    path: 'warden',
    fork: 'warden-3',
    tier: 3,
    maxLevel: 3,
    costs: [
      { essence: 20, plasma: 460, clots: 160 },
      { essence: 34, plasma: 800, clots: 300 },
      { essence: 55, plasma: 1300, clots: 500 },
    ],
    effects: { defense: 5, maxIntegrity: 100, regen: 16 },
    requires: ['warden-2'],
  },
  {
    id: 'warden-4',
    name: 'Вечная цитадель',
    description: 'Предел обороны: империю проще игнорировать, чем сломать.',
    path: 'warden',
    tier: 4,
    maxLevel: 3,
    costs: [
      { essence: 40, plasma: 1400, clots: 500 },
      { essence: 65, plasma: 2200, clots: 800 },
      { essence: 100, plasma: 3500, clots: 1300 },
    ],
    effects: { defense: 18, maxIntegrity: 150, regen: 18 },
    requires: ['warden-3a', 'warden-3b'],
    requiresAny: true,
  },

  // Ткач
  {
    id: 'weaver-1',
    name: 'Тишина',
    description: 'Угроза растёт заметно медленнее.',
    path: 'weaver',
    tier: 1,
    maxLevel: 3,
    costs: [{ essence: 4 }, { essence: 9, plasma: 120 }, { essence: 16, plasma: 260 }],
    /*
     * Подавление у пути было избыточным: суммарно оно доходило до 111% при
     * потолке снижения в 75%, и треть бюджета ветки просто пропадала. Излишек
     * перенесён в опыт и урон — величины, которые ни во что не упираются.
     */
    effects: { masking: 5, suppression: 0.05, xpYield: 0.15 },
  },
  {
    id: 'weaver-2',
    name: 'Изобилие',
    description: 'Каждый сектор отдаёт больше, чем должен.',
    path: 'weaver',
    tier: 2,
    maxLevel: 3,
    costs: [
      { essence: 10, plasma: 190 },
      { essence: 18, plasma: 360 },
      { essence: 30, plasma: 650 },
    ],
    effects: { plasmaYield: 0.22, essenceYield: 0.18, xpYield: 0.15 },
    requires: ['weaver-1'],
  },
  // Развилка Ткача: невидимость против логистики и охвата.
  {
    id: 'weaver-3a',
    name: 'Немыслимая сеть',
    description: 'Империи будто не существует: система ищет не там.',
    path: 'weaver',
    fork: 'weaver-3',
    tier: 3,
    maxLevel: 3,
    costs: [
      { essence: 20, plasma: 420, clots: 140 },
      { essence: 34, plasma: 740, clots: 260 },
      { essence: 55, plasma: 1200, clots: 440 },
    ],
    // Удар из невидимости: путь Ткача бьёт не сильно, а точно.
    effects: { suppression: 0.07, masking: 6, maxEnergy: 1, attack: 8, pierce: 5 },
    requires: ['weaver-2'],
  },
  {
    id: 'weaver-3b',
    name: 'Живая магистраль',
    description: 'Расстояний для империи почти не остаётся.',
    path: 'weaver',
    fork: 'weaver-3',
    tier: 3,
    maxLevel: 3,
    costs: [
      { essence: 20, plasma: 420, clots: 140 },
      { essence: 34, plasma: 740, clots: 260 },
      { essence: 55, plasma: 1200, clots: 440 },
    ],
    effects: { logistics: 3, plasmaYield: 0.15, xpYield: 0.3, attack: 5 },
    requires: ['weaver-2'],
  },
  {
    id: 'weaver-4',
    name: 'Империя без имени',
    description: 'Предел скрытности: система ищет врага, которого не существует.',
    path: 'weaver',
    tier: 4,
    maxLevel: 3,
    costs: [
      { essence: 40, plasma: 1300, clots: 420 },
      { essence: 65, plasma: 2100, clots: 700 },
      { essence: 100, plasma: 3300, clots: 1150 },
    ],
    effects: {
      masking: 12,
      suppression: 0.06,
      plasmaYield: 0.25,
      essenceYield: 0.25,
      attack: 14,
      pierce: 9,
    },
    requires: ['weaver-3a', 'weaver-3b'],
    requiresAny: true,
  },
]

/** Технологии добычи — 15 штук в трёх ветках. */
export const TECHS: TechDef[] = [
  // Плазма
  {
    id: 'flux-cores',
    name: 'Потоковые ядра',
    description: 'Базовое ускорение добычи плазмы.',
    branch: 'Плазма',
    tier: 1,
    maxLevel: 3,
    costs: [{ plasma: 55 }, { plasma: 120 }, { plasma: 250 }],
    effects: { plasmaYield: 0.16 },
  },
  {
    id: 'plasma-lattice',
    name: 'Плазменная решётка',
    description: 'Стабилизирует поток и повышает выход.',
    branch: 'Плазма',
    tier: 2,
    maxLevel: 3,
    costs: [
      { plasma: 200, clots: 30 },
      { plasma: 380, clots: 60 },
      { plasma: 680, clots: 110 },
    ],
    effects: { plasmaYield: 0.224 },
    requires: ['flux-cores'],
  },
  {
    id: 'hyper-osmosis',
    name: 'Гиперосмос',
    description: 'Выжимает плазму из всего, до чего дотягивается сеть.',
    branch: 'Плазма',
    tier: 3,
    maxLevel: 3,
    costs: [
      { plasma: 620, clots: 120, essence: 6 },
      { plasma: 1050, clots: 220, essence: 11 },
      { plasma: 1700, clots: 360, essence: 18 },
    ],
    effects: { plasmaYield: 0.32 },
    requires: ['plasma-lattice'],
  },
  {
    id: 'tidal-conduits',
    name: 'Приливные магистрали',
    description: 'Перекачивает избыток плазмы туда, где он нужен.',
    branch: 'Плазма',
    tier: 4,
    maxLevel: 3,
    costs: [
      { plasma: 1400, clots: 300, essence: 16 },
      { plasma: 2300, clots: 500, essence: 26 },
      { plasma: 3600, clots: 800, essence: 42 },
    ],
    effects: { plasmaYield: 0.416, xpYield: 0.16 },
    requires: ['hyper-osmosis'],
  },
  {
    id: 'crimson-tide',
    name: 'Багровый прилив',
    description: 'Предельная технология плазменной ветки.',
    branch: 'Плазма',
    tier: 5,
    maxLevel: 2,
    costs: [
      { plasma: 3000, clots: 700, essence: 40 },
      { plasma: 5000, clots: 1200, essence: 68 },
    ],
    effects: { plasmaYield: 0.56 },
    requires: ['tidal-conduits'],
  },

  // Сгустки
  {
    id: 'granulation',
    name: 'Гранулирование',
    description: 'Переработка теряет меньше материала.',
    branch: 'Сгустки',
    tier: 1,
    maxLevel: 3,
    costs: [
      { plasma: 70, clots: 12 },
      { plasma: 150, clots: 30 },
      { plasma: 300, clots: 65 },
    ],
    effects: { clotYield: 0.192 },
  },
  {
    id: 'clot-cascade',
    name: 'Каскад сгущения',
    description: 'Цепная реакция сгущения по всей сети.',
    branch: 'Сгустки',
    tier: 2,
    maxLevel: 3,
    costs: [
      { plasma: 240, clots: 50 },
      { plasma: 440, clots: 95 },
      { plasma: 780, clots: 170 },
    ],
    effects: { clotYield: 0.256 },
    requires: ['granulation'],
  },
  {
    id: 'harmonic-forge',
    name: 'Гармонический горн',
    description: 'Сгустки выходят прочнее и годятся в бой.',
    branch: 'Сгустки',
    tier: 3,
    maxLevel: 3,
    costs: [
      { plasma: 660, clots: 160, essence: 6 },
      { plasma: 1100, clots: 280, essence: 11 },
      { plasma: 1800, clots: 460, essence: 18 },
    ],
    effects: { clotYield: 0.32, attack: 3 },
    requires: ['clot-cascade'],
  },
  {
    id: 'iron-weave',
    name: 'Железное плетение',
    description: 'Технология, снятая с ферритиновых хранилищ.',
    branch: 'Сгустки',
    tier: 4,
    maxLevel: 3,
    costs: [
      { plasma: 1500, clots: 380, essence: 16 },
      { plasma: 2400, clots: 620, essence: 26 },
      { plasma: 3800, clots: 1000, essence: 42 },
    ],
    effects: { clotYield: 0.416, defense: 4 },
    requires: ['harmonic-forge'],
  },
  {
    id: 'obsidian-clot',
    name: 'Обсидиановый сгусток',
    description: 'Предельная технология ветки сгустков.',
    branch: 'Сгустки',
    tier: 5,
    maxLevel: 2,
    costs: [
      { plasma: 3200, clots: 900, essence: 40 },
      { plasma: 5200, clots: 1500, essence: 68 },
    ],
    effects: { clotYield: 0.56, attack: 6 },
    requires: ['iron-weave'],
  },

  // Эссенция
  {
    id: 'essence-distill',
    name: 'Дистилляция эссенции',
    description: 'Первый надёжный способ получать эссенцию.',
    branch: 'Эссенция',
    tier: 1,
    maxLevel: 3,
    costs: [
      { plasma: 120, clots: 30 },
      { plasma: 260, clots: 65 },
      { plasma: 520, clots: 130 },
    ],
    effects: { essenceYield: 0.224 },
  },
  {
    id: 'ether-siphon',
    name: 'Эфирный сифон',
    description: 'Вытягивает эссенцию из фонового шума системы.',
    branch: 'Эссенция',
    tier: 2,
    maxLevel: 3,
    costs: [
      { plasma: 340, clots: 80, essence: 3 },
      { plasma: 600, clots: 150, essence: 6 },
      { plasma: 1000, clots: 260, essence: 10 },
    ],
    effects: { essenceYield: 0.288, suppression: 0.05 },
    requires: ['essence-distill'],
  },
  {
    id: 'null-resonance',
    name: 'Нулевой резонанс',
    description: 'Гасит отклик иммунной сети на действия империи.',
    branch: 'Эссенция',
    tier: 3,
    maxLevel: 3,
    costs: [
      { plasma: 780, clots: 190, essence: 10 },
      { plasma: 1300, clots: 330, essence: 17 },
      { plasma: 2100, clots: 540, essence: 28 },
    ],
    effects: { essenceYield: 0.32, suppression: 0.09, masking: 3 },
    requires: ['ether-siphon'],
  },
  {
    id: 'quintessence',
    name: 'Квинтэссенция',
    description: 'Эссенция начинает воспроизводить сама себя.',
    branch: 'Эссенция',
    tier: 4,
    maxLevel: 3,
    costs: [
      { plasma: 1700, clots: 440, essence: 22 },
      { plasma: 2700, clots: 720, essence: 36 },
      { plasma: 4200, clots: 1150, essence: 58 },
    ],
    effects: { essenceYield: 0.448, xpYield: 0.192 },
    requires: ['null-resonance'],
  },
  {
    id: 'aether-crown',
    name: 'Эфирная корона',
    description: 'Предельная технология ветки эссенции.',
    branch: 'Эссенция',
    tier: 5,
    maxLevel: 2,
    costs: [
      { plasma: 3600, clots: 1000, essence: 55 },
      { plasma: 5800, clots: 1700, essence: 90 },
    ],
    effects: { essenceYield: 0.64, suppression: 0.1 },
    requires: ['quintessence'],
  },
]

export const MODULE_BY_ID: ReadonlyMap<string, ModuleDef> = new Map(MODULES.map(m => [m.id, m]))
export const DOCTRINE_BY_ID: ReadonlyMap<string, DoctrineDef> = new Map(
  DOCTRINES.map(d => [d.id, d]),
)
export const TECH_BY_ID: ReadonlyMap<string, TechDef> = new Map(TECHS.map(t => [t.id, t]))
